# Generated by Django 3.1.3 on 2021-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Supermercado',
            fields=[
                ('Nombre_Comercial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=30)),
                ('Marca', models.CharField(max_length=30)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Peso_Litros', models.CharField(max_length=20)),
            ],
        ),
    ]
