# Generated by Django 3.1.3 on 2021-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_supermercado',
            name='Imagen_Articulo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
