# Generated by Django 3.1.3 on 2021-01-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_auto_20210120_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_supermercado',
            name='Precio',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
